# Generated by Django 3.2.13 on 2022-08-08 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_language', models.TextField()),
                ('total_used', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_data', models.IntegerField()),
                ('no_answer', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('unchecked_answer', models.IntegerField()),
                ('checked_answer', models.IntegerField()),
                ('answer_ratio', models.IntegerField()),
                ('checked_answer_ratio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField()),
                ('post_title', models.CharField(max_length=100)),
                ('total_comment', models.IntegerField()),
                ('post_datetime', models.DateTimeField()),
                ('post_content', models.TextField()),
                ('post_component', models.CharField(blank=True, max_length=20, null=True)),
                ('code_lang', models.CharField(blank=True, max_length=20)),
                ('checked_answer', models.TextField(blank=True)),
                ('answer_datetime', models.DateTimeField(blank=True)),
                ('customer', models.ManyToManyField(blank=True, to='okkydokky.Customer')),
            ],
        ),
    ]
